# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Unknown'), (10, 'Patient'), (20, 'Nurse'), (30, 'Doctor'), (40, 'Admin')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'None'), (1, 'Account'), (2, 'Patient'), (3, 'Admin'), (4, 'Appointment'), (5, 'Medical Test'), (6, 'Prescription'), (7, 'Admission'), (8, 'Medical Info'), (9, 'Message')], default=0)),
                ('timePerformed', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_account', to='hospital.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('discharged_timestamp', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('Pneumonia', 'Pneumonia'), ('Congestive Heart Failure', 'Congestive Heart Failure'), ('Hardening of the arteries', 'Hardening of the arteries'), ('Heart Attack', 'Heart Attack'), ('Chronic Obstruction Lung Disease', 'Chronic Obstruction Lung Disease'), ('Stroke', 'Stroke'), ('Irregular Heartbeat', 'Irregular Heartbeat'), ('Congestive Heart Failure', 'Congestive Heart Failure'), ('Complications of procedures, devices, implants and grafts', 'Complications of procedures, devices, implants and grafts'), ('Mood Disorders', 'Mood Disorders'), ('Fluid and Electrolyte Disorders', 'Fluid and Electrolyte Disorders'), ('Urinary Infections', 'Urinary Infections'), ('Asthma', 'Asthma'), ('Diabetes mellitus with and without complications', 'Diabetes mellitus with and without complications'), ('Skin Infections', 'Skin Infections'), ('Gallbladder Disease', 'Gallbladder Disease'), ('Gastrointestinal Bleeding', 'Gastrointestinal Bleeding'), ('Hip Fracture', 'Hip Fracture'), ('Appendicitis', 'Appendicitis'), ('Other', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions_account', to='hospital.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_doctor', to='hospital.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(default='United States', max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodType', models.CharField(choices=[('A+', 'A+ Type'), ('B+', 'B+ Type'), ('AB+', 'AB+ Type'), ('O+', 'O+ Type'), ('A-', 'A- Type'), ('B-', 'B- Type'), ('AB-', 'AB- Type'), ('O-', 'O- Type')], max_length=10)),
                ('allergy', models.CharField(max_length=100)),
                ('alzheimer', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('stroke', models.BooleanField(default=False)),
                ('comments', models.CharField(max_length=700)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicalinfo_account', to='hospital.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('private', models.BooleanField(default=True)),
                ('completed', models.BooleanField()),
                ('image1', models.FileField(blank=True, null=True, upload_to='medtests/%Y/%m/%d')),
                ('image2', models.FileField(blank=True, null=True, upload_to='medtests/%Y/%m/%d')),
                ('image3', models.FileField(blank=True, null=True, upload_to='medtests/%Y/%m/%d')),
                ('image4', models.FileField(blank=True, null=True, upload_to='medtests/%Y/%m/%d')),
                ('image5', models.FileField(blank=True, null=True, upload_to='medtests/%Y/%m/%d')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaltests_doctor', to='hospital.Account')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaltests_patient', to='hospital.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=300)),
                ('body', models.CharField(max_length=1000)),
                ('sender_deleted', models.BooleanField(default=False)),
                ('target_deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sender', to='hospital.Account')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_target', to='hospital.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('sent_timestamp', models.DateTimeField(auto_now_add=True)),
                ('read_timestamp', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_account', to='hospital.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medication', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=30)),
                ('instruction', models.CharField(max_length=200)),
                ('refill', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_doctor', to='hospital.Account')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_patient', to='hospital.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('insurance', models.CharField(blank=True, max_length=50)),
                ('emergencyContactName', models.CharField(blank=True, max_length=50)),
                ('emergencyContactNumber', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.DateField(default=datetime.date(1000, 1, 1))),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('allergies', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('linkedEmergencyContact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles_contact', to='hospital.Account')),
                ('prefHospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles_prefhospital', to='hospital.Hospital')),
                ('primaryCareDoctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles_primarycaredoctor', to='hospital.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.Location'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_patient', to='hospital.Account'),
        ),
        migrations.AddField(
            model_name='admission',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.Profile'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
